apiVersion: v1
kind: Service
metadata:
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"
  labels:
    type: text-analyzer-service-type
spec:
  selector:
    type: text-analyzer-type
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

ports:
  strong:
    - type: "text-analyzer-type"
      value: 1