apiVersion: v1
kind: Service
metadata:
  labels:
    type: auth-service-type
spec:
  selector:
    type: auth-type
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

ports:
  required:
    strong:
      - type: "auth-type"
        value: 1