apiVersion: v1
kind: Pod
metadata:
  labels:
    type: virus-scanner-type
spec:
  containers:
    - name: virus-scanner
      image: giovaz94/mail-pipeline-general
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "120"
        - name: REDIS_HOST
          value: "redis-service"
        - name: SERVICE_NAME
          value: "virus-scanner"
        - name: PORT
          value: "80"
        - name: MAX_SIZE
          value: "800"
        - name: PORT_MESSAGE_ANALYZER_SERVICE
          type: "message-analyzer-service-type"
        - name: PORT_ATTACHMENT_MANAGER_SERVICE
          type: "attachment-manager-service-type"
        - name: MAX_CONNECTIONS
          value: "70"
        - name: PIPELINE_COUNT
          value: "1"
  restartPolicy: Always