apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    type: auth-service
spec:
  selector:
    app: auth
    type: auth-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
ports:
  required:
    strong:
      - name: "auth"
        value: 1