apiVersion: v1
kind: Service
metadata:
  name: image-service
  labels:
    type: image-service
spec:
  selector:
    app: image
    type: image-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
ports:
  required:
    strong:
      - name: "image"
        value: 2