apiVersion: v1
kind: Service
metadata:
  name: persistence-service
  labels:
    type: persistence-service
spec:
  selector:
    app: persistence
    type: persistence-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
ports:
  required:
    strong:
      - name: "persistence"
        value: 1