apiVersion: v1
kind: Service
metadata:
  name: recommender-service
  labels:
    type: recommender-service
spec:
  selector:
    app: recommender
    type: recommender-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
ports:
  required:
    strong:
      - name: "recommender"
        value: 1