apiVersion: v1
kind: Pod
metadata:
  name: webui
  labels:
    app: webui
spec:
  containers:
    - name: webui
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8001
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "150"
        - name: SERVICE_NAME
          value: "webUI"
        - name: PORT
          value: "8001"
        - name: OUTPUT_SERVICES
          value: '{"http://recommender-service:8005/request":"1","http://image-service:8004/request":"2","http://persistence-service:8003/request":"1","http://auth-service:8002/request":"1"}'
  restartPolicy: Always
ports:
  required:
    strong:
      - name: "image-service"
        value: 1
      - name: "persistence-service"
        value: 1
      - name: "auth-service"
        value: 1
      - name: "recommender-service"
        value: 1