apiVersion: v1
kind: Service
metadata:
  name: webui-service
spec:
  type: NodePort
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001  # Choose a port in the 30000–32767 range
ports:
  required:
    strong:
      - name: "webui"
        value: 1

