apiVersion: v1
kind: Pod
metadata:
  labels:
    type: webui-type
spec:
  containers:
    - name: webui
      image: giovaz94/tea-store-general
      imagePullPolicy: Always
      ports:
        - containerPort: 8001
      resources:
        requests:
          cpu: "10m"
          memory: "10M"
      env:
        - name: MCL
          value: "150"
        - name: SERVICE_NAME
          value: "webUI"
        - name: PORT
          value: "8001"
        - name: OUTPUT_SERVICES
          value: '{"http://recommender-service:8005/request":"1","http://image-service:8004/request":"2","http://persistence-service:8003/request":"1","http://auth-service:8002/request":"1"}'
        - name: DEP1
          value: "image-service-type"
        - name: DEP2
          value: "persistence-service-type"
        - name: DEP3
          value: "auth-service-type"
        - name: DEP4
          value: "recommender-service-type"

  restartPolicy: Always
ports:
  required:
    strong:
      - type: "image-service-type"
        value: 2
      - type: "persistence-service-type"
        value: 1
      - type: "auth-service-type"
        value: 1
      - type: "recommender-service-type"
        value: 1