name: my-k8s-app
resources:
  backend__2e133630_d389_4594_b863_a8ee53944713:
    name: backend__2e133630_d389_4594_b863_a8ee53944713
    options:
      dependsOn:
      - ${proxy_e07bcc48_8990_474c_87c0_7bad59141a98}
    properties:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: backend
        name: backend
      spec:
        containers:
        - image: k8s.gcr.io/pause:2.0
          name: backend-container
          resources:
            requests:
              cpu: 300m
              memory: 500M
        nodeName: k3d-k3s-default-agent-2
    type: kubernetes:core/v1:Pod
  backend__33629dc4_88fa_4587_b2f6_498f50b64962:
    name: backend__33629dc4_88fa_4587_b2f6_498f50b64962
    options:
      dependsOn:
      - ${proxy_e07bcc48_8990_474c_87c0_7bad59141a98}
    properties:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: backend
        name: backend
      spec:
        containers:
        - image: k8s.gcr.io/pause:2.0
          name: backend-container
          resources:
            requests:
              cpu: 300m
              memory: 500M
        nodeName: k3d-k3s-default-agent-2
    type: kubernetes:core/v1:Pod
  backend__8a3dae79_8ce3_49a1_b1a5_75ce9403963e:
    name: backend__8a3dae79_8ce3_49a1_b1a5_75ce9403963e
    options:
      dependsOn:
      - ${proxy_e07bcc48_8990_474c_87c0_7bad59141a98}
    properties:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: backend
        name: backend
      spec:
        containers:
        - image: k8s.gcr.io/pause:2.0
          name: backend-container
          resources:
            requests:
              cpu: 300m
              memory: 500M
        nodeName: k3d-k3s-default-agent-1
    type: kubernetes:core/v1:Pod
  proxy__078508ba_f9e1_4abf_af84_334c99714789:
    name: proxy__078508ba_f9e1_4abf_af84_334c99714789
    options: {}
    properties:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: proxy
        name: proxy
      spec:
        containers:
        - image: k8s.gcr.io/pause:2.0
          name: proxy-container
          resources:
            requests:
              cpu: 450m
              memory: 600M
        nodeName: k3d-k3s-default-agent-0
    type: kubernetes:core/v1:Pod
  proxy_e07bcc48_8990_474c_87c0_7bad59141a98:
    name: proxy_e07bcc48_8990_474c_87c0_7bad59141a98
    options: {}
    properties:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: proxy
        name: proxy
      spec:
        containers:
        - image: k8s.gcr.io/pause:2.0
          name: proxy-container
          resources:
            requests:
              cpu: 450m
              memory: 600M
        nodeName: k3d-k3s-default-agent-1
    type: kubernetes:core/v1:Pod
runtime: yaml
