apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    type: backend-type
spec:
  containers:
    - name: backend-container
      image: k8s.gcr.io/pause:2.0
      resources:
        requests:
          cpu: "300m"
          memory: "500M"
ports:
  strong:
    - type: "proxy-type"
      id: PORT_PROXY
      value: 1