apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  containers:
    - name: proxy-container
      image: k8s.gcr.io/pause:2.0
      resources:
        requests:
          cpu: "450m"
          memory: "600M"