apiVersion: v1
kind: Pod
metadata:
  labels:
    type: support-type
spec:
  containers:
    - name: support-container
      image: k8s.gcr.io/pause:2.0
      resources:
        requests:
          cpu: "450m"
          memory: "600M"
      env:
        - name: "PROVA"
          type: "support-service-type"