apiVersion: v1
kind: Service
metadata:
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"
  labels:
    type: support-service-type
spec:
  selector:
    type: support-type
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

ports:
  required:
    strong:
      - type: "support-type"
        value: 1