apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80          # Port that the service will expose
      targetPort: 8080  # Port the container listens on
      nodePort: 30007   # Port exposed on the node (optional, can be auto-assigned)
ports:
  required:
    strong:
      - name: "backend"
        value: 1
