apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: proxy-container
      image: k8s.gcr.io/pause:2.0
      resources:
        requests:
          cpu: "300m"
          memory: "500M"
